// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3aQK3ljLQk4qBz8R0EgWFH3gSXjPswtE',
    appId: '1:14802278834:web:f3cb9ff25d322b1f4d6cab',
    messagingSenderId: '14802278834',
    projectId: 'signup-fcab5',
    authDomain: 'signup-fcab5.firebaseapp.com',
    storageBucket: 'signup-fcab5.appspot.com',
    measurementId: 'G-KL5574FWMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgoBOZz6YzNESYzdXDmleUR_c6aPGLrQ',
    appId: '1:14802278834:android:806c81de7a7d10ab4d6cab',
    messagingSenderId: '14802278834',
    projectId: 'signup-fcab5',
    storageBucket: 'signup-fcab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxI0_ZFnMlnoqSIr1lFOpHL409AajJtcA',
    appId: '1:14802278834:ios:856ae543a59b5d724d6cab',
    messagingSenderId: '14802278834',
    projectId: 'signup-fcab5',
    storageBucket: 'signup-fcab5.appspot.com',
    iosBundleId: 'com.orchid.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxI0_ZFnMlnoqSIr1lFOpHL409AajJtcA',
    appId: '1:14802278834:ios:856ae543a59b5d724d6cab',
    messagingSenderId: '14802278834',
    projectId: 'signup-fcab5',
    storageBucket: 'signup-fcab5.appspot.com',
    iosBundleId: 'com.orchid.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3aQK3ljLQk4qBz8R0EgWFH3gSXjPswtE',
    appId: '1:14802278834:web:2ebb31eb930db4df4d6cab',
    messagingSenderId: '14802278834',
    projectId: 'signup-fcab5',
    authDomain: 'signup-fcab5.firebaseapp.com',
    storageBucket: 'signup-fcab5.appspot.com',
    measurementId: 'G-H81D0MBDK1',
  );
}
